$path = 'app\orders\[orderId]\page.tsx'
$txt = Get-Content -Raw -LiteralPath $path
$txt = $txt -replace 'onClick=\{\(\) => setUpdatesOpen\(true\)\}', 'onClick={openUpdates}'
$txt = $txt -replace '\{updatesOpen && \(', '{updatesVisible && ('
$txt = $txt -replace 'className="absolute inset-0 bg-black/30"\s*\n\s*onClick=\{\(\) => setUpdatesOpen\(false\)\}', 'className={"absolute inset-0 bg-black/30 transition-opacity duration-200 " + (updatesOpen ? "opacity-100" : "opacity-0")}\n              onClick={closeUpdates}'
$txt = $txt -replace 'className="absolute right-0 top-0 h-full w\[82%\] max-w-xs bg-white border-l border-black/15 p-5 grid gap-4"', 'className={"absolute right-0 top-0 h-full w-[82%] max-w-xs bg-white border-l border-black/15 p-5 grid gap-4 transition-transform duration-200 ease-out " + (updatesOpen ? "translate-x-0" : "translate-x-full")}'
$txt = $txt -replace 'onClick=\{\(\) => setUpdatesOpen\(false\)\}', 'onClick={closeUpdates}'
$txt = $txt -replace '(?s)<div className="grid gap-3">\s*\{steps.map\(\(step, idx\) => \{.*?\}\)\}\s*</div>', '<div className="relative pl-5">\n                <div className="absolute left-[6px] top-2 bottom-2 w-px bg-black/20" />\n                <div className="grid gap-4">\n                  {steps.map((step, idx) => {\n                    const active = idx <= currentStep;\n                    return (\n                      <div key={step} className="relative flex items-start gap-3">\n                        <span\n                          className={`mt-1 w-3 h-3 rounded-full border ${active ? "bg-black border-black" : "bg-white border-black/30"}`}\n                        />\n                        <div className="text-sm">\n                          <div className={active ? "font-semibold" : "text-[var(--muted)]"}>{step}</div>\n                          <div className="text-xs text-[var(--muted)]">{active ? "Completed" : "Pending"}</div>\n                        </div>\n                      </div>\n                    );\n                  })}\n                </div>\n              </div>'
Set-Content -LiteralPath $path -Value $txt
